### ISSUE TITLE
Any::copyInto fails after running a task twice

### ISSUE THREAD

**Issue by DaniGarciaLopez** [captain-yoshi/BehaviorTree.MTC#30]
I noticed that there is a runtime error after running a task twice:
```bash
[bt_demo-1] terminate called after throwing an instance of 'std::runtime_error'
[bt_demo-1]   what():  Any::copyInto fails
```
Both task are executed in separate subtrees so they should have a fully independant blackboard:
![tree](https://github.com/user-attachments/assets/1096eb6c-5534-45d4-a211-17f6df810962)

The exception throws the second time `CreateMTCCurrentState` is called at [new_value.copyInto(previous_any)](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/f5e98fd751523fd2797e5353cb9f1cc765587cb4/include/behaviortree_cpp/blackboard.h#L305). It seems this is updating a previous value in the blackboard instead of declaring a new one. It appears that `stage` is being reused from the previous iteration, even though it should be isolated because it's declared in another subtree

This is the relevant part of the stack trace:
```bash
[bt_demo-1] #10   Source "/home/dani/bt_ws/src/BehaviorTree.MTC/src/create_mtc_current_state.cpp", line 24, in tick [0x5d721568d98a]
[bt_demo-1]          21:   // Upcast to base class
[bt_demo-1]          22:   moveit::task_constructor::StagePtr base_stage = stage;
[bt_demo-1]          23: 
[bt_demo-1]       >  24:   setOutput("stage", base_stage);
[bt_demo-1]          25: 
[bt_demo-1]          26:   return NodeStatus::SUCCESS;
[bt_demo-1]          27: }
[bt_demo-1] #9    Source "/home/dani/bt_ws/install/include/behaviortree_cpp/tree_node.h", line 596, in setOutput<std::shared_ptr<moveit::task_constructor::Stage> > [0x5d721568fdb1]
[bt_demo-1]         593:   }
[bt_demo-1]         594: 
[bt_demo-1]         595:   remapped_key = stripBlackboardPointer(remapped_key);
[bt_demo-1]       > 596:   config().blackboard->set(static_cast<std::string>(remapped_key), value);
[bt_demo-1]         597: 
[bt_demo-1]         598:   return {};
[bt_demo-1]         599: }
[bt_demo-1] #8    Source "/home/dani/bt_ws/install/include/behaviortree_cpp/blackboard.h", line 305, in set<std::shared_ptr<moveit::task_constructor::Stage> > [0x5d721568f36f]
[bt_demo-1]         302:     else
[bt_demo-1]         303:     {
[bt_demo-1]         304:       // copy only if the type is compatible
[bt_demo-1]       > 305:       new_value.copyInto(previous_any);
[bt_demo-1]         306:     }
[bt_demo-1]         307:     entry.sequence_id++;
[bt_demo-1]         308:     entry.stamp = std::chrono::steady_clock::now().time_since_epoch();
[bt_demo-1] #7    Source "/home/dani/bt_ws/install/include/behaviortree_cpp/utils/safe_any.hpp", line 357, in copyInto [0x5d721563f8e3]
[bt_demo-1]         354:   }
[bt_demo-1]         355:   else
[bt_demo-1]         356:   {
[bt_demo-1]       > 357:     throw std::runtime_error("Any::copyInto fails");
[bt_demo-1]         358:   }
[bt_demo-1]         359: }
```

### Steps to reproduce the issue:
In `examples/bt_demo.cpp`. Modify the tree:
```xml
<root BTCPP_format="4">
  <BehaviorTree ID="MainTree">
    <Sequence name="root">
      <Repeat num_cycles="2">
        <SubTree ID="PlanTask"/>
      </Repeat>
    </Sequence>
  </BehaviorTree>

  <BehaviorTree ID="PlanTask">
    <Sequence>
      <InitializeMTCTask task="{mtc_task}"/>
      <CreateMTCCurrentState stage="{stage}"/>
      <MoveMTCStageToTask parent="{mtc_task}"
                          child="{stage}"/>
      <PlanMTCTask task="{mtc_task}"
                   max_solutions="5"/>
    </Sequence>
  </BehaviorTree>
</root>
```
And set `MainTree` as a default:
```cpp
factory.registerBehaviorTreeFromText(xml_text);
auto tree = factory.createTree("MainTree");
```

Is this a bug in our side, BehaviorTree.CPP issue or I just simply misundertood how subtrees work?

**Comment by captain-yoshi** [comment]
Can you test again by commenting this [line](https://github.com/captain-yoshi/BehaviorTree.MTC/blob/master/include/behaviortree_mtc/move_mtc_stage.h#L34C9-L34C75) and see if it helps ?

```cpp
// any_child_ptr.assign(nullptr);  // set blackboard value to nullptr
```

**Comment by DaniGarciaLopez** [comment]
Commenting out that line apparently solves the issue. As far as I could test, everything works fine now!

**Comment by DaniGarciaLopez** [comment]
Executing the `bt_pick_place` task twice was still throwing the exception. I had to also comment out [this line](https://github.com/captain-yoshi/BehaviorTree.MTC/blob/d861eb853cd6a78457a6dde92c634461d70f6ac9/include/behaviortree_mtc/blackboard_helper.h#L35).

**Comment by captain-yoshi** [comment]
Thanks for testing this.

I'm not an expert with the blackboard, but my reasoning was to invalidate a std::move in disguise by setting the blackboard variable to a null pointer.

Will add a hotfix later today and see if there is a bug in the BT library.
